Update

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,6 +9,19 @@ parameters:
   - apply
   - destroy
 
+- name: taint
+  displayName: 'Taint a resource?'
+  type: string
+  default: 'no'
+  values:
+  - yes
+  - no
+
+- name: taintResource
+  displayName: 'Resource to taint'
+  type: string
+  default: ''
+
 pr:
   branches:
     include:
@@ -68,6 +81,22 @@ jobs:
       allowTelemetryCollection: false
 
   # ---------------------------------------------------
+  # Terraform Taint
+  # ---------------------------------------------------
+  - task: Bash@3
+    displayName: 'Terraform Taint Resource'
+    condition: eq('${{ parameters.taint }}', 'yes')
+    inputs:
+      targetType: 'inline'
+      script: |
+        if [ -z "${{ parameters.taintResource }}" ]; then
+        echo "ERROR: taintResource parameter is empty."
+        exit 1
+        fi
+        echo "Tainting resource: ${{ parameters.taintResource }}"
+        terraform -chdir=$(Build.SourcesDirectory)/infrastructure taint ${{ parameters.taintResource }}
+
+  # ---------------------------------------------------
   # Terraform Format
   # ---------------------------------------------------
   - task: Bash@3
@@ -100,7 +129,7 @@ jobs:
       environmentServiceNameAzureRM: $(SERVICE_CONNECTION)
 
   # ---------------------------------------------------
-  # Terraform Apply (manual approval)
+  # Terraform Apply
   # ---------------------------------------------------
   - task: TerraformTaskV4@4
     displayName: 'Terraform Apply'
